export const reservations = [
    {
        id: 1,
        name: 'Royalt Apartment',
        dateStart: '02/05SEP21',
        dateEnd: '2020-01-02',
        time: '10:00',
        people: 2,
        status: 'done',
        createdAt: '2020-01-01',
        updatedAt: '2020-01-01',
        location: 'BARCELONA',
        street: 'Carrer de Pallars, 171, 08005',
        img: require('../../assets/images/reservations/1.png'),
        guests: [
            {name: 'Juan', lastname: 'Perez', id: 1, img: require('../../assets/images/guests/1.png')},
            {name: 'Juan', lastname: 'Perez', id: 2, img: require('../../assets/images/guests/2.png')},
            {name: 'Juan', lastname: 'Perez', id: 3, img: require('../../assets/images/guests/3.png')},
            {name: 'Juan', lastname: 'Perez', id: 4, img: require('../../assets/images/guests/4.png')},
            {name: 'Juan', lastname: 'Perez', id: 5, img: require('../../assets/images/guests/5.png')},
        ]
    }, 
    {
        id: 2,
        name: 'Networking Event',
        dateStart: '09/15OCT21',
dateEnd: '2020-01-02',
        time: '10:00',
        people: 2,
        status: 'pending',
        createdAt: '2020-01-01',
        updatedAt: '2020-01-01',
        location: 'BARCELONA',
        street: 'Carrer de Pallars, 171, 08005',
        img: require('../../assets/images/reservations/2.png'),
        guests: [
            {name: 'Juan', lastname: 'Perez', id: 1, img: require('../../assets/images/guests/1.png')},
            {name: 'Juan', lastname: 'Perez', id: 2, img: require('../../assets/images/guests/2.png')},
            {name: 'Juan', lastname: 'Perez', id: 3, img: require('../../assets/images/guests/3.png')},
            {name: 'Juan', lastname: 'Perez', id: 4, img: require('../../assets/images/guests/4.png')},
            {name: 'Juan', lastname: 'Perez', id: 5, img: require('../../assets/images/guests/5.png')},
        ]
    }, 
    {
        id: 3,
        name: 'Royalt Apartment',
        dateStart: '2020-01-01',
        dateEnd: '2020-01-02',
        time: '10:00',
        people: 2,
        status: 'done',
        createdAt: '2020-01-01',
        updatedAt: '2020-01-01',
        location: 'BARCELONA',
        street: 'Carrer de Pallars, 171, 08005',
        img: require('../../assets/images/reservations/1.png'),
        guests: [
            {name: 'Juan', lastname: 'Perez', id: 1, img: require('../../assets/images/guests/1.png')},
            {name: 'Juan', lastname: 'Perez', id: 2, img: require('../../assets/images/guests/2.png')},
            {name: 'Juan', lastname: 'Perez', id: 3, img: require('../../assets/images/guests/3.png')},
            {name: 'Juan', lastname: 'Perez', id: 4, img: require('../../assets/images/guests/4.png')},
            {name: 'Juan', lastname: 'Perez', id: 5, img: require('../../assets/images/guests/5.png')},
        ]
    }, 
]